### ISSUE TITLE
Add short url alias

### ISSUE THREAD

**Issue by mildronize** [mildronize/blog-v8#7]
```toml
title = "Dealing with more than 100 secrets on GitHub Actions using Mozilla SOPS and Azure Key Vault"

[taxonomies]
categories = [ "GitHub Actions" ]
tags = [ "GitHub Actions", "Mozila SOPS", "Azure Key Vault" ]

[extra]
id = "suzlta6"
unsplashImgCoverId = "NWmcp5fE_4M"
```

add script to auto add alias field for redirect
```
aliases = ["/s/suzlta6"]
```

Add copy to clipboard
